services:
  sistemats-middleware:
    image: hotplugindev/sistemats-rest-middleware:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - PRODUCTION_ENVIRONMENT=true
    restart: unless-stopped
